FROM kyroy/gochecks:latest

LABEL "com.github.actions.name"="GoChecks Test"
LABEL "com.github.actions.description"="Executes go tests."
LABEL "com.github.actions.icon"="play"
LABEL "com.github.actions.color"="green"

ENTRYPOINT ["/cmd/gochecks", "test"]
