FROM kyroy/gochecks:latest

LABEL "com.github.actions.name"="GoChecks fmt"
LABEL "com.github.actions.description"="Executes go fmt."
LABEL "com.github.actions.icon"="file-text"
LABEL "com.github.actions.color"="blue"

ENTRYPOINT ["/cmd/gochecks", "fmt"]
